### ISSUE TITLE
Error with spades_assembly.sh

### ISSUE THREAD

**Issue by MiaCoco** [BU-ISCIII/plasmidID#21] opened 2022-02-17 15:06 UTC
I am currently working with WGS data and would like to use your programme PlasmidID. After installation, I tried to run my fasta files and encountered this error.

[logs.zip](https://github.com/BU-ISCIII/plasmidID/files/8089704/logs.zip)
![Capture](https://user-images.githubusercontent.com/52832402/154509891-db1a26b6-710f-42ff-9fce-6cff2e5757cf.PNG)

**Comment by saramonzon** [comment] 2022-02-17 15:27
Hello @MiaCoco ! Thanks for reaching out!
It seems that your problem is related with spades more than with plasmidID, I'm going to try and reproduce the error in case it's due to the spades version being installed by conda. You could try and assembly the sample prior to plasmidID using [unicycler](https://github.com/rrwick/Unicycler) and then pass the contigs as input to plasmidID with `--contigs` parameter.
I'll check that and come back to you, but you can try this meanwhile, being this the recommended way so you can control the assembly quality!
Hope this helps!

**Comment by MiaCoco** [comment] 2022-02-19 15:54
DearSara, I ran my files (from Illumina pair-end reads) through the unicycler and got the assembly.fasta file. Then I passed this file to plasmidID with the --contigs parameter and encountered a new error. Attached are my logs, data, kmer and assembly.fasta

[assembly.zip](https://github.com/BU-ISCIII/plasmidID/files/8102541/assembly.zip)

[data.zip](https://github.com/BU-ISCIII/plasmidID/files/8102537/data.zip)
[logs.zip](https://github.com/BU-ISCIII/plasmidID/files/8102539/logs.zip)

**Comment by saramonzon** [comment] 2022-02-20 13:59
Mm they are issues with the installation, now with prokka, did you install it with conda I assume? I have to review the `environment.yml`..I'll try to sort this out this week, sorry for the inconvenience!
In the meantime you can use the singularity container here which seems to be working fine: https://depot.galaxyproject.org/singularity/plasmidid%3A1.6.5--hdfd78af_0

You can download it and use it this way making sure you have all the input files in your working directory: 
```
wget https://depot.galaxyproject.org/singularity/plasmidid%3A1.6.5--hdfd78af_0
singularity exec depot.galaxyproject.org-singularity-plasmidid-1.6.5--hdfd78af_0.img plasmidID --help 
```

**Comment by MiaCoco** [comment] 2022-02-21 12:23
Dear Sara, I run in another error. :( I don't know what to do anymore. 
![PlasmidID_ERROR3](https://user-images.githubusercontent.com/52832402/154954237-5a69a793-59ed-4bb6-a91b-58b073c0ff7a.PNG)

**Comment by saramonzon** [comment] 2022-02-21 12:29
I had that error too, it is a funny one 😆 , when you install singularity with apt-get install singularity, a game is installed instead of the container command!
You can install it with conda! https://anaconda.org/conda-forge/singularity

**Comment by MiaCoco** [comment] 2022-02-21 12:51
First, I would like to thank you for your time and desire to help. I know that sometimes it is difficult when people work with tools and interfaces that they are not comfortable with (like me (Windows user))... and again error 😆 ...
![error4](https://user-images.githubusercontent.com/52832402/154959103-753b935f-68e6-4d6b-8c82-6c1d55f5e763.PNG)
![Uploading error4.PNG…]()

**Comment by saramonzon** [comment] 2022-02-21 12:53
In your ls you see that the image you downloaded is named `plasmidid:1.6.5--hdfd78af_0` without the `.img`
So you should use 
```
singularity exec plasmidid:1.6.5--hdfd78af_0 plasmidID --help
```

**Comment by MiaCoco** [comment] 2022-02-21 13:04
I tried that and other forms.. 
![error5](https://user-images.githubusercontent.com/52832402/154960699-3d0f237f-9aed-4cc6-8e5d-f53750702e2a.PNG)
Do I have to activate somehow singularity first? 
![eroror4_1](https://user-images.githubusercontent.com/52832402/154961399-1091d692-2eb6-4811-a5a7-d2a0cf28457f.PNG)

**Comment by MiaCoco** [comment] 2022-02-21 13:19
![eror6](https://user-images.githubusercontent.com/52832402/154963084-f35d4237-c430-46ec-bb5f-feee03a9e701.PNG)

**Comment by saramonzon** [comment] 2022-02-21 13:37
Aahh ok, I see, you have singularity 2.4 version, you need > 3.5. 
Create a new env for singularity:
```
conda create -n singularity -c conda-forge singularity==3.8.5
conda activate singularity
singularity exec plasmidid:1.6.5--hdfd78af_0 plasmidID --help
```

**Comment by MiaCoco** [comment] 2022-02-23 09:41
After all your advice I was able to install everything and it works perfectly. I would like to ask you one more thing, even if it is not related to this problem. 
I downloaded the database and at the second step I got this error message
![error 7](https://user-images.githubusercontent.com/52832402/155294202-2a39cc6d-759b-4eab-86ed-0641838b607e.PNG)
filter_fasta.sh: command not found

**Comment by saramonzon** [comment] 2022-02-23 10:31
You are searching the `filter_fasta.sh` in `/bin`, you need to indicate that it is the bin folder in your path, if you are in plasmidID folder you can use `./bin/filter_fasta.sh`

**Comment by MiaCoco** [comment] 2022-02-23 10:47
Hmmm... I tried that, but still nothing. Maybe the singularity is playing tricks on us and that's why it does not work?
![err8](https://user-images.githubusercontent.com/52832402/155304628-6a695ce9-7ba7-4648-bc15-e1b2607e540b.PNG)

**Comment by saramonzon** [comment] 2022-02-23 10:49
this can be run outside of singularity safely I think, it's just a bash script, but you need to have all those scripts in your path:
```
export PATH=$PATH:/path/to/plasmid_folder
export PATH=$PATH//path/to/plasmidid_folder/bin
```

**Comment by MiaCoco** [comment] 2022-02-23 10:55
![err9](https://user-images.githubusercontent.com/52832402/155305773-65385e7b-32d6-42b0-a7a5-edb90f32032b.PNG)
I think this is the longest issue on this git hub xD

**Comment by saramonzon** [comment] 2022-02-23 10:58
you need to replace `/path/to/plasmidid` with the actual path in your pc to plasmidID folder!

**Comment by saramonzon** [comment] 2022-03-01 11:34
I think I can close this issue, if you have any problem please re-open or open another one! :)

**Closed as completed by saramonzon** 2022-03-01 11:34 UTC

**Comment by MiaCoco** [comment] 2022-03-01 12:45
Yes, I Agree. Thank you soo much !

Get Outlook za Android<https://aka.ms/AAb9ysg>
________________________________
